apiVersion: v1
kind: Service

metadata:
  name: ai-threat-service

spec:
  type: NodePort

  selector:
    app: ai-threat-dashboard

  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30007